# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgeneric.proto\x1a\x19google/protobuf/any.proto\"T\n\x17protobuf_insert_request\x12\x10\n\x08keyspace\x18\x01 \x01(\t\x12\'\n\tprotobufs\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\"^\n\x17protobuf_select_request\x12\x10\n\x08keyspace\x18\x01 \x01(\t\x12\r\n\x05table\x18\x02 \x01(\t\x12\x0e\n\x06\x63olumn\x18\x03 \x01(\t\x12\x12\n\nconstraint\x18\x04 \x01(\t\"q\n\x17protobuf_update_request\x12\x10\n\x08keyspace\x18\x01 \x01(\t\x12\r\n\x05table\x18\x02 \x01(\t\x12\x0e\n\x06\x63olumn\x18\x03 \x01(\t\x12\x12\n\nconstraint\x18\x04 \x01(\t\x12\x11\n\tnew_value\x18\x05 \x01(\t\"^\n\x17protobuf_delete_request\x12\x10\n\x08keyspace\x18\x01 \x01(\t\x12\r\n\x05table\x18\x02 \x01(\t\x12\x0e\n\x06\x63olumn\x18\x03 \x01(\t\x12\x12\n\nconstraint\x18\x04 \x01(\t\"=\n\x1aprotobuf_droptable_request\x12\x10\n\x08keyspace\x18\x01 \x01(\t\x12\r\n\x05table\x18\x02 \x01(\t\"\'\n\x17protobuf_error_response\x12\x0c\n\x04\x65rrs\x18\x01 \x03(\t\"?\n\x18protobuf_select_response\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x11\n\tprotobufs\x18\x02 \x03(\x0c\x32\xc8\x02\n\tDBGeneric\x12<\n\x06Insert\x12\x18.protobuf_insert_request\x1a\x18.protobuf_error_response\x12=\n\x06Select\x12\x18.protobuf_select_request\x1a\x19.protobuf_select_response\x12<\n\x06Update\x12\x18.protobuf_update_request\x1a\x18.protobuf_error_response\x12<\n\x06\x44\x65lete\x12\x18.protobuf_delete_request\x1a\x18.protobuf_error_response\x12\x42\n\tDropTable\x12\x1b.protobuf_droptable_request\x1a\x18.protobuf_error_responseB\x0bZ\t../commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t../common'
  _globals['_PROTOBUF_INSERT_REQUEST']._serialized_start=44
  _globals['_PROTOBUF_INSERT_REQUEST']._serialized_end=128
  _globals['_PROTOBUF_SELECT_REQUEST']._serialized_start=130
  _globals['_PROTOBUF_SELECT_REQUEST']._serialized_end=224
  _globals['_PROTOBUF_UPDATE_REQUEST']._serialized_start=226
  _globals['_PROTOBUF_UPDATE_REQUEST']._serialized_end=339
  _globals['_PROTOBUF_DELETE_REQUEST']._serialized_start=341
  _globals['_PROTOBUF_DELETE_REQUEST']._serialized_end=435
  _globals['_PROTOBUF_DROPTABLE_REQUEST']._serialized_start=437
  _globals['_PROTOBUF_DROPTABLE_REQUEST']._serialized_end=498
  _globals['_PROTOBUF_ERROR_RESPONSE']._serialized_start=500
  _globals['_PROTOBUF_ERROR_RESPONSE']._serialized_end=539
  _globals['_PROTOBUF_SELECT_RESPONSE']._serialized_start=541
  _globals['_PROTOBUF_SELECT_RESPONSE']._serialized_end=604
  _globals['_DBGENERIC']._serialized_start=607
  _globals['_DBGENERIC']._serialized_end=935
# @@protoc_insertion_point(module_scope)
