# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import generic_pb2 as generic__pb2


class DBGenericStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/DBGeneric/Insert',
                request_serializer=generic__pb2.protobuf_insert_request.SerializeToString,
                response_deserializer=generic__pb2.protobuf_error_response.FromString,
                )
        self.Select = channel.unary_unary(
                '/DBGeneric/Select',
                request_serializer=generic__pb2.protobuf_select_request.SerializeToString,
                response_deserializer=generic__pb2.protobuf_select_response.FromString,
                )
        self.Update = channel.unary_unary(
                '/DBGeneric/Update',
                request_serializer=generic__pb2.protobuf_update_request.SerializeToString,
                response_deserializer=generic__pb2.protobuf_error_response.FromString,
                )
        self.Delete = channel.unary_unary(
                '/DBGeneric/Delete',
                request_serializer=generic__pb2.protobuf_delete_request.SerializeToString,
                response_deserializer=generic__pb2.protobuf_error_response.FromString,
                )
        self.DropTable = channel.unary_unary(
                '/DBGeneric/DropTable',
                request_serializer=generic__pb2.protobuf_droptable_request.SerializeToString,
                response_deserializer=generic__pb2.protobuf_error_response.FromString,
                )


class DBGenericServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Select(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DBGenericServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=generic__pb2.protobuf_insert_request.FromString,
                    response_serializer=generic__pb2.protobuf_error_response.SerializeToString,
            ),
            'Select': grpc.unary_unary_rpc_method_handler(
                    servicer.Select,
                    request_deserializer=generic__pb2.protobuf_select_request.FromString,
                    response_serializer=generic__pb2.protobuf_select_response.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=generic__pb2.protobuf_update_request.FromString,
                    response_serializer=generic__pb2.protobuf_error_response.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=generic__pb2.protobuf_delete_request.FromString,
                    response_serializer=generic__pb2.protobuf_error_response.SerializeToString,
            ),
            'DropTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DropTable,
                    request_deserializer=generic__pb2.protobuf_droptable_request.FromString,
                    response_serializer=generic__pb2.protobuf_error_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DBGeneric', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DBGeneric(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DBGeneric/Insert',
            generic__pb2.protobuf_insert_request.SerializeToString,
            generic__pb2.protobuf_error_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Select(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DBGeneric/Select',
            generic__pb2.protobuf_select_request.SerializeToString,
            generic__pb2.protobuf_select_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DBGeneric/Update',
            generic__pb2.protobuf_update_request.SerializeToString,
            generic__pb2.protobuf_error_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DBGeneric/Delete',
            generic__pb2.protobuf_delete_request.SerializeToString,
            generic__pb2.protobuf_error_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DropTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DBGeneric/DropTable',
            generic__pb2.protobuf_droptable_request.SerializeToString,
            generic__pb2.protobuf_error_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
